logger:
  use: zapLogger
  environment: dev
  loglevel: debug
  filename: tmp/team_action_dev.log
#db:
#  use: postgres
#  connection:
#    enabled: true
#    host: 192.168.2.2
#    port: 5432
#    userName: dbuser
#    password: dbuser
#    database: team_action_dev
db:
  use: sqlite3
  connection:
    enabled: true
    host:
    port: 
    userName: 
    password: 
    database: tmp/team_action_dev.db
