server:
  name: team_action
  host: localhost
  port: 3000
log:
  code: zap
  level: debug
  file_name: tmp/team_action_dev.log
#database:
#  code: sqldb
#  driver_name: postgres
#  url_address: "host=localhost port=5432 user=postgres password=postgres dbname=team_action_dev sslmode=disable"
#  db_name: team_action_dev
database:
  code: sqldb
  driver_name: sqlite3
  url_address: "tmp/team_action_dev.db"
